// libs/pseo-config.js — Seed data & configuration for Programmatic SEO
// All combinational expansion is driven from this single source of truth.

const PSEO_CONFIG = {
    // ── Core categories ──
    categories: [
      "ai-humanizer",
      "ai-detector",
      "plagiarism-checker",
      "paraphrasing-tool",
      "essay-writer",
      "content-rewriter",
      "grammar-checker",
    ],
  
    // ── Target personas ──
    personas: [
      { slug: "students", label: "Students", pain: "Academic integrity flags on AI-assisted essays" },
      { slug: "bloggers", label: "Bloggers", pain: "SEO content flagged as AI by Google" },
      { slug: "copywriters", label: "Copywriters", pain: "Client deliverables detected as AI-written" },
      { slug: "researchers", label: "Researchers", pain: "Journal submissions rejected by AI screening" },
      { slug: "marketers", label: "Marketers", pain: "Ad copy and landing pages penalised for AI patterns" },
      { slug: "freelancers", label: "Freelancers", pain: "Upwork/Fiverr clients running AI checks on deliverables" },
      { slug: "agencies", label: "Agencies", pain: "Scaling content production without AI detection risk" },
      { slug: "teachers", label: "Teachers", pain: "Need to verify student work authenticity" },
      { slug: "journalists", label: "Journalists", pain: "Maintaining credibility with AI-assisted drafts" },
      { slug: "seo", label: "SEO & Content Teams", pain: "High-volume content flagged by Google's helpful content system" },
{ slug: "business-emails", label: "Business Professionals", pain: "Emails and proposals sounding robotic" },
{ slug: "legal", label: "Legal Professionals", pain: "AI-drafted contracts lacking authoritative tone" },
{ slug: "academic-writing", label: "Academic Writers", pain: "Research papers rejected by AI screening" },
{ slug: "youtube", label: "YouTube Creators", pain: "AI scripts sounding unnatural when spoken" },
{ slug: "linkedin", label: "LinkedIn Users", pain: "Posts flagged as AI-generated" },
{ slug: "non-native-speakers", label: "Non-Native Speakers", pain: "AI writing lacks natural fluency" },
{ slug: "reddit", label: "Reddit Users", pain: "AI posts detected and downvoted" },
{ slug: "job-seekers", label: "Job Seekers", pain: "Resumes flagged as AI-written by HR tools" },
{ slug: "ecommerce", label: "E-commerce Sellers", pain: "Product descriptions flagged on marketplaces" },
    ],
  
    // ── Competitor / comparison tools ──
    tools: [
      { slug: "quillbot", label: "QuillBot" },
      { slug: "undetectable-ai", label: "Undetectable AI" },
      { slug: "writebot", label: "WriteBot" },
      { slug: "humbot", label: "Humbot" },
      { slug: "bypass-ai", label: "BypassAI" },
      { slug: "stealthwriter", label: "StealthWriter" },
      { slug: "hix-bypass", label: "HIX Bypass" },
      { slug: "netus-ai", label: "Netus AI" },
      { slug: "phrasly", label: "Phrasly" },
      { slug: "smodin", label: "Smodin" },
      { slug: "wordai", label: "WordAI" },
      { slug: "spinbot", label: "SpinBot" },
      { slug: "bypassgpt", label: "BypassGPT" },
{ slug: "supwriter", label: "SupWriter" },
{ slug: "writehuman", label: "WriteHuman" },
{ slug: "aiseo", label: "AISEO" },
    ],
  
    // ── AI detectors we bypass ──
    detectors: [
      { slug: "turnitin", label: "Turnitin" },
      { slug: "gptzero", label: "GPTZero" },
      { slug: "zerogpt", label: "ZeroGPT" },
      { slug: "originality-ai", label: "Originality.ai" },
      { slug: "copyleaks", label: "Copyleaks" },
      { slug: "sapling", label: "Sapling" },
      { slug: "writer-ai-detector", label: "Writer AI Detector" },
      { slug: "crossplag", label: "Crossplag" },
      { slug: "grammarly", label: "Grammarly AI Detector" },
      { slug: "scribbr", label: "Scribbr" },
    ],
  
    // ── Locations (top English-speaking + EU markets) ──
    locations: [
      { slug: "united-states", label: "United States", lang: "en" },
      { slug: "united-kingdom", label: "United Kingdom", lang: "en" },
      { slug: "canada", label: "Canada", lang: "en" },
      { slug: "australia", label: "Australia", lang: "en" },
      { slug: "germany", label: "Germany", lang: "de" },
      { slug: "france", label: "France", lang: "fr" },
      { slug: "spain", label: "Spain", lang: "es" },
      { slug: "india", label: "India", lang: "en" },
      { slug: "netherlands", label: "Netherlands", lang: "nl" },
      { slug: "czech-republic", label: "Czech Republic", lang: "cs" },
      { slug: "brazil", label: "Brazil", lang: "pt" },
      { slug: "mexico", label: "Mexico", lang: "es" },
      { slug: "italy", label: "Italy", lang: "it" },
      { slug: "japan", label: "Japan", lang: "ja" },
      { slug: "south-korea", label: "South Korea", lang: "ko" },
    ],
  
    // ── Use cases ──
    useCases: [
      { slug: "essays", label: "Essays" },
      { slug: "blog-posts", label: "Blog Posts" },
      { slug: "research-papers", label: "Research Papers" },
      { slug: "product-descriptions", label: "Product Descriptions" },
      { slug: "email-copy", label: "Email Copy" },
      { slug: "social-media", label: "Social Media Posts" },
      { slug: "cover-letters", label: "Cover Letters" },
      { slug: "seo-content", label: "SEO Content" },
      { slug: "ad-copy", label: "Ad Copy" },
      { slug: "technical-writing", label: "Technical Writing" },
      { slug: "creative-writing", label: "Creative Writing" },
      { slug: "reports", label: "Reports" },
      { slug: "assignments", label: "Assignments" },
{ slug: "resumes", label: "Resumes" },
{ slug: "linkedin-posts", label: "LinkedIn Posts" },
{ slug: "youtube-scripts", label: "YouTube Scripts" },
{ slug: "reddit-posts", label: "Reddit Posts" },
{ slug: "newsletters", label: "Newsletters" },
{ slug: "whitepapers", label: "Whitepapers" },
{ slug: "case-studies", label: "Case Studies" },
    ],
  
    // ── AI models ──
    aiModels: [
      { slug: "chatgpt", label: "ChatGPT" },
      { slug: "gpt-4", label: "GPT-4" },
      { slug: "claude", label: "Claude" },
      { slug: "gemini", label: "Gemini" },
      { slug: "llama", label: "Llama" },
      { slug: "copilot", label: "Copilot" },
      { slug: "jasper", label: "Jasper AI" },
      { slug: "perplexity", label: "Perplexity" },
      { slug: "grok", label: "Grok" },
{ slug: "deepseek", label: "DeepSeek" },
{ slug: "mistral", label: "Mistral" },
    ],
  
    // ── Glossary terms ──
    glossaryTerms: [
      { slug: "ai-detection", label: "AI Detection" },
      { slug: "ai-humanization", label: "AI Humanization" },
      { slug: "perplexity-score", label: "Perplexity Score" },
      { slug: "burstiness", label: "Burstiness" },
      { slug: "nlp", label: "Natural Language Processing" },
      { slug: "transformer-model", label: "Transformer Model" },
      { slug: "token", label: "Token" },
      { slug: "fine-tuning", label: "Fine-Tuning" },
      { slug: "prompt-engineering", label: "Prompt Engineering" },
      { slug: "hallucination", label: "AI Hallucination" },
      { slug: "watermarking", label: "AI Watermarking" },
      { slug: "temperature", label: "Temperature (LLM)" },
      { slug: "zero-shot", label: "Zero-Shot Learning" },
      { slug: "few-shot", label: "Few-Shot Learning" },
      { slug: "embedding", label: "Text Embedding" },
      { slug: "rag", label: "RAG (Retrieval-Augmented Generation)" },
      { slug: "large-language-model", label: "Large Language Model (LLM)" },
      { slug: "ai-content-detection", label: "AI Content Detection" },
      { slug: "text-classifier", label: "Text Classifier" },
      { slug: "paraphrasing", label: "Paraphrasing" },
    ],
  
    // ── Languages for translation pages ──
    languages: [
      { code: "es", label: "Spanish", native: "Español" },
      { code: "fr", label: "French", native: "Français" },
      { code: "de", label: "German", native: "Deutsch" },
      { code: "pt", label: "Portuguese", native: "Português" },
      { code: "it", label: "Italian", native: "Italiano" },
      { code: "ja", label: "Japanese", native: "日本語" },
      { code: "ko", label: "Korean", native: "한국어" },
      { code: "zh", label: "Chinese", native: "中文" },
      { code: "ar", label: "Arabic", native: "العربية" },
      { code: "hi", label: "Hindi", native: "हिन्दी" },
      { code: "ru", label: "Russian", native: "Русский" },
      { code: "tr", label: "Turkish", native: "Türkçe" },
      { code: "pl", label: "Polish", native: "Polski" },
      { code: "nl", label: "Dutch", native: "Nederlands" },
      { code: "cs", label: "Czech", native: "Čeština" },
    ],
    keywordPages: [
        { slug: "humanizeai", title: "Humanize AI", keyword: "humanize ai" },
        { slug: "ai-humanizer", title: "AI Humanizer", keyword: "ai humanizer" },
        { slug: "humanize-ai-text", title: "Humanize AI Text", keyword: "humanize ai text" },
        { slug: "free-humanizer", title: "Free AI Humanizer", keyword: "free ai humanizer" },
        { slug: "ai-detector", title: "Free AI Detector", keyword: "ai detector free" },
        { slug: "text-humanizer", title: "Text Humanizer", keyword: "text humanizer" },
        { slug: "chatgpt-humanizer", title: "ChatGPT Humanizer", keyword: "chatgpt humanizer" },
        { slug: "ai-to-human-text", title: "AI to Human Text Converter", keyword: "ai to human text" },
        { slug: "undetectable-ai-writer", title: "Undetectable AI Writer", keyword: "undetectable ai writer" },
        { slug: "ai-rewriter", title: "AI Rewriter", keyword: "ai rewriter" },
        { slug: "anti-ai-detection", title: "Anti AI Detection Tool", keyword: "anti ai detection" },
      ],
      
      alternativesPages: [
        { slug: "quillbot-alternatives", tool: "QuillBot", keyword: "quillbot alternatives" },
        { slug: "bypassgpt-alternatives", tool: "BypassGPT", keyword: "bypassgpt alternatives" },
        { slug: "undetectable-ai-alternatives", tool: "Undetectable AI", keyword: "undetectable ai alternatives" },
        { slug: "humbot-alternatives", tool: "Humbot", keyword: "humbot alternatives" },
        { slug: "hix-bypass-alternatives", tool: "HIX Bypass", keyword: "hix bypass alternatives" },
        { slug: "stealthwriter-alternatives", tool: "StealthWriter", keyword: "stealthwriter alternatives" },
        { slug: "smodin-alternatives", tool: "Smodin", keyword: "smodin alternatives" },
        { slug: "writehuman-alternatives", tool: "WriteHuman", keyword: "writehuman alternatives" },
        { slug: "supwriter-alternatives", tool: "SupWriter", keyword: "supwriter alternatives" },
      ],
  };
  
  export default PSEO_CONFIG;